if(EditorApplication.isPlayingOrWillChangePlaymode || EditorApplication.isCompiling)throw new System.Exception("Editor must be idle");
var current=UnityEngine.SceneManagement.SceneManager.GetActiveScene();if(current.isDirty)throw new System.Exception("Scene has pending edits");
const string path="Assets/Scenes/Duty01_Laundry.unity",folder="Assets/Prototype/Duty01";
if(System.IO.File.Exists(path)||AssetDatabase.IsValidFolder(folder))throw new System.Exception("Duty assets exist; do not overwrite");
var scene=UnityEditor.SceneManagement.EditorSceneManager.OpenScene("Assets/Scenes/Save01_Progress.unity");
AssetDatabase.CreateFolder("Assets/Prototype","Duty01");
Material Mat(string n,Color c){var m=new Material(Shader.Find("Universal Render Pipeline/Lit"));m.name=n;m.color=c;m.SetFloat("_Smoothness",.2f);AssetDatabase.CreateAsset(m,folder+"/"+n+".mat");return m;}
var wall=Mat("Laundry plaster",new Color(.55f,.61f,.58f));var floor=Mat("Laundry floor",new Color(.24f,.29f,.28f));var white=Mat("Enamel",new Color(.76f,.79f,.70f));var dark=Mat("Rubber",new Color(.10f,.15f,.17f));var blue=Mat("Work blue",new Color(.23f,.53f,.63f));var brass=Mat("Tool brass",new Color(.62f,.43f,.18f));var rueMat=Mat("Rue sage",new Color(.29f,.43f,.33f));var dexMat=Mat("Dex burgundy",new Color(.43f,.22f,.24f));var navy=AssetDatabase.LoadAssetAtPath<Material>("Assets/Prototype/Guard01/Guard navy.mat");
var root=new GameObject("Laundry module");root.transform.position=new Vector3(-2,0,9);var room=root.AddComponent<PrisonGame.Prototype.LaundryRoom>();
GameObject Box(string n,Vector3 p,Vector3 size,Material m,bool solid=true){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(root.transform,false);g.transform.localPosition=p;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=m;if(!solid)UnityEngine.Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
Transform Mark(string n,Vector3 p){var g=new GameObject(n);g.transform.SetParent(root.transform,false);g.transform.localPosition=p;return g.transform;}
BoxCollider Zone(string n,Vector3 p,Vector3 size){var t=Mark(n,p);var c=t.gameObject.AddComponent<BoxCollider>();c.size=size;c.isTrigger=true;return c;}
void Label(string n,string value,Vector3 p,float yaw,float size=.022f){var t=Mark(n,p);t.localRotation=Quaternion.Euler(0,yaw,0);var tm=t.gameObject.AddComponent<TextMesh>();tm.text=value;tm.fontSize=48;tm.characterSize=size;tm.anchor=TextAnchor.MiddleCenter;tm.alignment=TextAlignment.Center;tm.color=new Color(.96f,.93f,.79f);t.gameObject.SetActive(false);var d=t.gameObject.AddComponent<PrisonGame.Prototype.WorldLabelDepth>();var so=new SerializedObject(d);so.FindProperty("labelShader").objectReferenceValue=AssetDatabase.LoadAssetAtPath<Shader>("Assets/Prototype/Scripts/WorldLabel.shader");so.ApplyModifiedPropertiesWithoutUndo();t.gameObject.SetActive(true);}
Box("Laundry floor",new Vector3(4.5f,-.1f,4),new Vector3(9,.2f,8),floor);Box("Laundry ceiling",new Vector3(4.5f,3.3f,4),new Vector3(9,.2f,8),wall);
Box("Laundry west wall",new Vector3(0,1.6f,4),new Vector3(.2f,3.2f,8),wall);Box("Laundry north wall",new Vector3(4.5f,1.6f,8),new Vector3(9,3.2f,.2f),wall);
Box("Laundry south wall",new Vector3(6,1.6f,0),new Vector3(6,3.2f,.2f),wall);Box("Laundry entry lintel",new Vector3(1.5f,2.9f,0),new Vector3(3,.6f,.2f),wall);
Box("Supply dividing south",new Vector3(9,1.6f,1.3f),new Vector3(.2f,3.2f,2.6f),wall);Box("Supply dividing north",new Vector3(9,1.6f,6.2f),new Vector3(.2f,3.2f,3.6f),wall);Box("Supply doorway lintel",new Vector3(9,2.9f,3.5f),new Vector3(.2f,.6f,1.8f),wall);
Box("Supply floor",new Vector3(11,-.1f,4),new Vector3(4,.2f,4),floor);Box("Supply ceiling",new Vector3(11,3.3f,4),new Vector3(4,.2f,4),wall);
Box("Supply back",new Vector3(13,1.6f,4),new Vector3(.2f,3.2f,4),wall);foreach(float z in new[]{2f,6f})Box("Supply wall",new Vector3(11,1.6f,z),new Vector3(4,3.2f,.2f),wall);
Box("Connecting floor",new Vector3(1.5f,-.1f,-1),new Vector3(3,.2f,2),floor);Box("Connecting ceiling",new Vector3(1.5f,3.3f,-1),new Vector3(3,.2f,2),wall);foreach(float x in new[]{0f,3f})Box("Connecting wall",new Vector3(x,1.6f,-1),new Vector3(.2f,3.2f,2),wall);
foreach(float x in new[]{1.4f,3.6f,5.8f}){Box("Laundry machine",new Vector3(x,.7f,7.25f),new Vector3(1.5f,1.4f,1.2f),white);Box("Machine door",new Vector3(x,.76f,6.63f),new Vector3(1,.85f,.05f),dark);Box("Machine glass",new Vector3(x,.76f,6.59f),new Vector3(.72f,.62f,.04f),blue,false);Box("Machine controls",new Vector3(x,1.2f,6.59f),new Vector3(1,.12f,.03f),dark,false);}
room.workArea=Zone("Work area",new Vector3(3.7f,1.1f,5.4f),new Vector3(6,2.2f,2));
foreach(float z in new[]{4.4f,6.4f})Box("Work boundary",new Vector3(3.7f,.008f,z),new Vector3(6,.012f,.07f),blue,false);foreach(float x in new[]{.7f,6.7f})Box("Work boundary",new Vector3(x,.008f,5.4f),new Vector3(.07f,.012f,2),blue,false);
room.supplyArea=Zone("Unauthorized supply area",new Vector3(11,1.1f,4),new Vector3(4,2.2f,4));
Box("Tall linen shelving - cover",new Vector3(6.4f,1.1f,2.7f),new Vector3(.6f,2.2f,2.2f),dark);foreach(float y in new[]{.5f,1.1f,1.7f})Box("Folded towels",new Vector3(6.04f,y,2.7f),new Vector3(.22f,.32f,1.5f),white,false);
Box("Supply shelf",new Vector3(11.5f,.8f,5.4f),new Vector3(2.4f,.15f,.8f),dark);Box("Shelf support",new Vector3(11.5f,.35f,5.4f),new Vector3(.2f,.7f,.6f),dark);
var tool=Box("Valve key",new Vector3(11.4f,.96f,5.25f),new Vector3(.4f,.12f,.16f),brass);tool.AddComponent<PrisonGame.Prototype.LaundryInteraction>().kind=PrisonGame.Prototype.LaundryInteraction.Kind.Tool;room.toolVisual=tool;
var board=Box("Assigned laundry duty board",new Vector3(1.5f,1.35f,.65f),new Vector3(1.1f,.9f,.12f),dark);board.AddComponent<PrisonGame.Prototype.LaundryInteraction>().kind=PrisonGame.Prototype.LaundryInteraction.Kind.Board;
Label("Duty board text","LAUNDRY DUTY\nREPORT HERE  [E]\n2 min shift / 1 min work",new Vector3(1.5f,1.4f,.57f),0,.013f);
Label("Laundry sign","LAUNDRY",new Vector3(1.5f,2.9f,-.12f),0,.026f);Label("Work sign","WORK AREA\nQuiet conversation allowed",new Vector3(3.7f,2.2f,7.85f),0,.018f);
Label("Supply sign","SUPPLY ROOM\nAUTHORIZED STAFF ONLY",new Vector3(8.85f,2.65f,3.5f),90,.016f);
GameObject Person(string n,Vector3 pos,Material clothes,PrisonGame.Prototype.LaundryInteraction.Kind kind){var t=Mark(n,pos);t.localRotation=Quaternion.Euler(0,180,0);var c=t.gameObject.AddComponent<CapsuleCollider>();c.center=new Vector3(0,.98f,0);c.height=1.96f;c.radius=.24f;var rig=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prototype/Art03Rig/M5_Rigged.prefab"),t);rig.transform.localRotation=Quaternion.Euler(0,180,0);foreach(var r in rig.GetComponentsInChildren<SkinnedMeshRenderer>()){var ms=r.sharedMaterials;for(int i=0;i<ms.Length;i++)if(ms[i].name=="M5_Ochre"||ms[i].name=="M5_BlueGrey")ms[i]=clothes;r.sharedMaterials=ms;}t.gameObject.AddComponent<PrisonGame.Prototype.LaundryInteraction>().kind=kind;Label(n+" label",n,pos+new Vector3(0,2.2f,0),0,.016f);return t.gameObject;}
Person("Rue",new Vector3(4.7f,0,6.25f),rueMat,PrisonGame.Prototype.LaundryInteraction.Kind.Rue);Person("Dex",new Vector3(2.6f,0,1.9f),dexMat,PrisonGame.Prototype.LaundryInteraction.Kind.Dex);
room.guard=Person("Officer Vale",new Vector3(7.5f,0,6.6f),navy,PrisonGame.Prototype.LaundryInteraction.Kind.Guard).transform;room.eyes=new GameObject("Eyes").transform;room.eyes.SetParent(room.guard,false);room.eyes.localPosition=new Vector3(0,1.72f,.1f);room.workLook=Mark("Work watch point",new Vector3(3.7f,0,5.4f));room.deskLook=Mark("Desk watch point",new Vector3(8.6f,0,7.7f));room.guard.rotation=Quaternion.LookRotation(room.workLook.position-room.guard.position);
Box("Vale desk",new Vector3(8.1f,.9f,7.5f),new Vector3(1.2f,.15f,.65f),dark);
foreach(var p in new[]{new Vector3(2,2.9f,3),new Vector3(5.5f,2.9f,6),new Vector3(11,2.9f,4)}){var l=Mark("Warm laundry light",p).gameObject.AddComponent<Light>();l.type=LightType.Point;l.range=7;l.intensity=3;l.color=new Color(1,.86f,.65f);l.shadows=LightShadows.None;Box("Ceiling diffuser",p+Vector3.up*.2f,new Vector3(.7f,.05f,.7f),white,false);}
var prefab=PrefabUtility.SaveAsPrefabAssetAndConnect(root,folder+"/LaundryModule.prefab",InteractionMode.AutomatedAction);
foreach(string n in new[]{"Hall north end lower","Hall north end upper"}){var o=GameObject.Find(n);if(o==null)throw new System.Exception("Missing "+n);UnityEngine.Object.DestroyImmediate(o);}
var player=GameObject.Find("Player");var duty=player.AddComponent<PrisonGame.Prototype.LaundryDuty>();duty.room=root.GetComponent<PrisonGame.Prototype.LaundryRoom>();player.AddComponent<PrisonGame.Prototype.PlayerInventory>();player.AddComponent<PrisonGame.Prototype.LaundryHud>();
// Start at the new assignment; the older cell/common area remains connected to the south.
player.transform.SetPositionAndRotation(new Vector3(-.5f,.05f,8.2f),Quaternion.identity);
UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene,path);AssetDatabase.SaveAssets();return "Saved Duty01_Laundry and reusable LaundryModule prefab; connected to existing corridor, two contacts, guard, machines and supply room.";
