if(!EditorApplication.isPlaying)throw new System.Exception("Enter fresh Save01 Play first.");
var p=GameObject.Find("Player");var save=p.GetComponent<PrisonGame.Prototype.SampleSaveGame>();var actor=p.GetComponent<PrisonGame.Prototype.PlayerInteraction>();var stock=p.GetComponent<PrisonGame.Prototype.SnackSupplies>();var request=p.GetComponent<PrisonGame.Prototype.SnackRequest>();var clock=request.Clock;var tray=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SnackAssembly>();var shelf=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SnackShelf>();var inspection=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SupplyInspection>();var guard=p.GetComponent<PrisonGame.Prototype.GuardSuspicion>();
var results=new System.Collections.Generic.List<string>();void Check(bool ok,string name){if(!ok)throw new System.Exception("FAIL: "+name);results.Add("PASS: "+name);}
const string path="Temp/Save01Checks/roundtrip.json";System.IO.Directory.CreateDirectory("Temp/Save01Checks");
var fresh=save.Capture(actor);Check(save.SaveTo(actor,path),"Fresh paused game saves to an isolated fixture");
Check(!save.SaveTo(null,path),"A different acting player cannot save");
request.Accept(actor,request.Customer);stock.CollectStarter();for(int i=0;i<3;i++)tray.Interact(actor);request.Deliver(actor,request.Customer);tray.Interact(actor);
Check(inspection.Closed && request.Delivered==1 && tray.Stage==1,"Fixture uses a real sale, closure and partially assembled second pack");
var parcel=UnityEngine.Object.FindObjectsByType<PrisonGame.Prototype.PrototypePickup>(FindObjectsSortMode.None).First(x=>x.GetComponent<PrisonGame.Prototype.SnackPackItem>()==null);actor.PickUp(parcel);
var state=save.Capture(actor);state.player.suspicion=55;state.player.position=new Vector3(2.4f,.05f,3.5f);state.player.yaw=110;state.player.pitch=-15;save.Restore(actor,state);
Check(save.SaveTo(actor,path),"In-progress state replaces the existing save");Check(System.IO.File.Exists(path+".bak"),"Replacing a save retains the previous file as a backup");
save.Restore(actor,fresh);Check(stock.Money==0 && !inspection.Started && tray.Stage==0,"Restoring fresh state clears newer progression");
Check(save.LoadFrom(actor,path),"Disk round trip succeeds");
Check(stock.Money==3 && stock.Sales==1 && stock.Crackers==0 && stock.Fruit==1 && stock.Wrappers==1,"Money, sale count and consumed ingredients restore exactly");
Check(request.Accepted && request.Delivered==1 && request.Paid==3 && request.DueAt==state.player.dueAt,"Request delivery, payment and original deadline restore");
Check(tray.Stage==1 && tray.WorkingPlayer==actor,"Unfinished tray restores its working player");
Check(actor.HeldItem==parcel && !parcel.GetComponent<Collider>().enabled,"Carried parcel restores attachment and disabled collision");
Check(Vector3.Distance(p.transform.position,state.player.position)<.001f && Quaternion.Angle(p.transform.rotation,Quaternion.Euler(0,110,0))<.01f,"Player position and yaw restore");
Check(Quaternion.Angle(p.GetComponentInChildren<Camera>().transform.localRotation,Quaternion.Euler(-15,0,0))<.01f,"Camera pitch restores");
Check(guard.Level==55 && inspection.Closed && inspection.ReopensAt==state.world.reopensAt,"Suspicion and active closure restore");
Check(clock.Paused && Time.timeScale==0 && !p.GetComponent<PrisonGame.Prototype.FirstPersonController>().ControlsActive,"Loading stays paused with mouse released");
// Finish remaining work after loading; free the parcel through fresh snapshot-held flag.
state=save.Capture(actor);state.world.parcels[0].held=false;state.world.parcels[0].position=new Vector3(-4,1,-1);save.Restore(actor,state);
tray.Interact(actor);tray.Interact(actor);Check(actor.HeldItem!=null && actor.HeldItem.GetComponent<PrisonGame.Prototype.SnackPackItem>()!=null,"Loaded unfinished tray can produce a usable pack");
var held=save.Capture(actor);
var stored=JsonUtility.FromJson<PrisonGame.Prototype.SampleSaveData>(JsonUtility.ToJson(held));stored.world.shelfInstalled=true;stored.world.packs[0].held=false;stored.world.packs[0].position=new Vector3(-3.08f,1.55f,-2.85f);stored.world.packs[0].velocity=new Vector3(.1f,0,0);stored.world.doors[0].opening=true;stored.world.doors[0].position+=Vector3.forward*.5f;
save.Restore(actor,stored);var storedAgain=save.Capture(actor);
Check(actor.HeldItem==null && request.ReadyPacks==1 && Vector3.Distance(storedAgain.world.packs[0].position,stored.world.packs[0].position)<.001f,"Stored pack restores world position and ready-pack count");
Check(storedAgain.world.packs[0].velocity==stored.world.packs[0].velocity && storedAgain.world.doors[0].opening && storedAgain.world.doors[0].position==stored.world.doors[0].position,"Item velocity and partially opened door restore");
save.Restore(actor,fresh);save.Restore(actor,held);save.Restore(actor,held);
Check(request.ReadyPacks==1 && actor.HeldItem.GetComponent<PrisonGame.Prototype.SnackPackItem>().Source==stock,"Repeated load neither duplicates held packs nor loses their owner");
request.Deliver(actor,request.Customer);Check(request.Delivered==2 && stock.Money==6 && request.ReadyPacks==0,"Restored carried pack sells exactly once");
clock.SetPaused(false);clock.Advance(50);clock.SetPaused(true);bool free;stock.Restock(out free);for(int i=0;i<3;i++)tray.Interact(actor);request.Deliver(actor,request.Customer);shelf.Interact(actor);
Check(request.Complete && stock.Money==0 && shelf.Installed && !inspection.Closed,"Loaded loop remains completable through shelf purchase");
var completed=save.Capture(actor);save.Restore(actor,fresh);save.Restore(actor,completed);Check(shelf.Installed && request.Complete && request.Paid==9 && stock.Money==0,"Completion, actual payment and purchased shelf restore");
var late=save.Capture(actor);late.player.accepted=true;late.player.delivered=2;late.player.paid=5;late.player.money=5;late.player.completedLate=false;late.world.minutes=late.player.dueAt+1;save.Restore(actor,late);Check(request.IsLate && request.DeliveryPrice==2 && request.Paid==5,"Overdue load retains reduced price and earlier mixed payment");
var before=JsonUtility.ToJson(save.Capture(actor));var bad=JsonUtility.FromJson<PrisonGame.Prototype.SampleSaveData>(before);bad.version=999;System.IO.File.WriteAllText("Temp/Save01Checks/bad.json",JsonUtility.ToJson(bad));
Check(!save.LoadFrom(actor,"Temp/Save01Checks/bad.json") && JsonUtility.ToJson(save.Capture(actor))==before,"Unsupported version is rejected without changing progress");
System.IO.File.WriteAllText("Temp/Save01Checks/bad.json","{broken");Check(!save.LoadFrom(actor,"Temp/Save01Checks/bad.json") && JsonUtility.ToJson(save.Capture(actor))==before,"Malformed JSON is rejected without changing progress");
bad=JsonUtility.FromJson<PrisonGame.Prototype.SampleSaveData>(before);bad.player.money=-1;System.IO.File.WriteAllText("Temp/Save01Checks/bad.json",JsonUtility.ToJson(bad));Check(!save.LoadFrom(actor,"Temp/Save01Checks/bad.json") && stock.Money==5,"Invalid economy data is rejected");
bad=JsonUtility.FromJson<PrisonGame.Prototype.SampleSaveData>(before);bad.scene="OtherScene";System.IO.File.WriteAllText("Temp/Save01Checks/bad.json",JsonUtility.ToJson(bad));Check(!save.LoadFrom(actor,"Temp/Save01Checks/bad.json"),"Another scene's save is rejected");
Check(!save.LoadFrom(actor,"Temp/Save01Checks/missing.json"),"Missing save reports failure");
Check(!save.SaveTo(actor,"Temp/Save01Checks"),"Unwritable destination reports failure");
Check(JsonUtility.ToJson(save.Capture(actor))==before,"Failed file operations preserve current progress");
clock.SetPaused(false);Check(!save.SaveTo(actor,path) && !save.LoadFrom(actor,path),"Save and load refuse unpaused simulation");clock.SetPaused(true);
Check(save.LoadFrom(actor,path),"Last good save remains loadable after failures");
System.IO.File.WriteAllLines("../docs/images/save01-checks.txt",results);return string.Join("\n",results);
