// Guard sight, suspicion, feedback and deadline integration. Run fresh Guard01 Play.
if(!EditorApplication.isPlaying)throw new System.Exception("Enter Play first.");
var player=GameObject.Find("Player");var actor=player.GetComponent<PrisonGame.Prototype.PlayerInteraction>();var stock=player.GetComponent<PrisonGame.Prototype.SnackSupplies>();var movement=player.GetComponent<PrisonGame.Prototype.FirstPersonController>();var cc=player.GetComponent<CharacterController>();var cam=player.GetComponentInChildren<Camera>();
var box=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SnackSupplyBox>();var tray=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SnackAssembly>();var shelf=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.SnackShelf>();var inmate=UnityEngine.Object.FindFirstObjectByType<PrisonGame.Prototype.PrototypeInmate>();var hud=player.GetComponent<PrisonGame.Prototype.SnackLoopHud>();
if(stock.StarterCollected||actor.HeldItem!=null)throw new System.Exception("Use fresh Play state.");
var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;var capture=movement.GetType().GetMethod("SetCursorCaptured",flags);var tick=actor.GetType().GetMethod("Update",flags);var seek=actor.GetType().GetMethod("FindTarget",flags);
var start=player.transform.position;var rotation=player.transform.rotation;var cameraRotation=cam.transform.localRotation;
var settings=UnityEngine.InputSystem.InputSystem.settings;var bg=settings.backgroundBehavior;var input=settings.editorInputBehaviorInPlayMode;UnityEngine.InputSystem.Keyboard keyboard=null;
var results=new System.Collections.Generic.List<string>();void Check(bool value,string text){if(!value)throw new System.Exception("FAIL: "+text);results.Add("PASS: "+text);}
void Press(UnityEngine.InputSystem.Key key){UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState());UnityEngine.InputSystem.InputSystem.Update();UnityEngine.InputSystem.InputSystem.QueueStateEvent(keyboard,new UnityEngine.InputSystem.LowLevel.KeyboardState(key));UnityEngine.InputSystem.InputSystem.Update();tick.Invoke(actor,null);Physics.SyncTransforms();}
void Use(PrisonGame.Prototype.PrototypeInteractable target,Vector3 place,Vector3 aim){cc.enabled=false;player.transform.position=place;cc.enabled=true;cam.transform.rotation=Quaternion.LookRotation(aim-cam.transform.position);Physics.SyncTransforms();capture.Invoke(movement,new object[]{true});seek.Invoke(actor,null);if(actor.Target!=target)throw new System.Exception("Cannot target "+target.name+"; hit "+(actor.Target==null?"nothing":actor.Target.name));Press(UnityEngine.InputSystem.Key.E);}
void Supply()=>Use(box,new Vector3(2.7f,.05f,3.8f),box.transform.position);
void Assemble(){for(int i=0;i<3;i++)Use(tray,new Vector3(2.7f,.05f,3.8f),tray.transform.position);}
void Sell()=>Use(inmate,new Vector3(2.4f,.05f,3.5f),inmate.transform.position+Vector3.up*1.2f);
void Shelf()=>Use(shelf,new Vector3(-3.4f,.05f,-1.3f),new Vector3(-3.08f,1.47f,-2.85f));
var request=player.GetComponent<PrisonGame.Prototype.SnackRequest>();
var buyer=inmate.GetComponent<PrisonGame.Prototype.SnackPackBuyer>();
var suspicion=player.GetComponent<PrisonGame.Prototype.GuardSuspicion>();var guard=suspicion.Observer;var guardHud=player.GetComponent<PrisonGame.Prototype.GuardSuspicionHud>();var clock=request.Clock;var driver=player.GetComponent<PrisonGame.Prototype.SoloClockDriver>();
var guardTick=guardHud.GetType().GetMethod("Update",flags);bool suspicionEnabled=suspicion.enabled,driverEnabled=driver.enabled;GameObject blocker=null,second=null;var guardRotation=guard.transform.rotation;
void Place(Vector3 pos){cc.enabled=false;player.transform.position=pos;cc.enabled=true;Physics.SyncTransforms();}
void Clear(){Place(new Vector3(6.8f,.05f,4.8f));suspicion.Step(10);guardTick.Invoke(guardHud,null);}
try{
    settings.backgroundBehavior=UnityEngine.InputSystem.InputSettings.BackgroundBehavior.IgnoreFocus;settings.editorInputBehaviorInPlayMode=UnityEngine.InputSystem.InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;keyboard=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Keyboard>();
    suspicion.enabled=false;driver.enabled=false;clock.SetPaused(false);Clear();
    Check(Vector3.Dot(-guard.GetComponentInChildren<Animator>().transform.forward,guard.transform.forward)>.999f,"Visible character facing matches the guard sight direction");
    Check(suspicion.Level==0 && !suspicion.Inside,"Ordinary common-room space starts without suspicion");
    Place(new Vector3(6.8f,.05f,5f));Check(guard.CanSee(actor),"Guard can see a player on the normal side of the boundary");suspicion.Step(2);Check(suspicion.Level==0,"Being visible outside the restricted area does not raise suspicion");
    cc.Move(new Vector3(0,0,.7f));Physics.SyncTransforms();Check(guard.Area.Contains(actor),"Player can physically cross the marked boundary without hidden collision");
    suspicion.Step(1);Check(suspicion.Rising && Mathf.Abs(suspicion.Level-12.5f)<.001f,"Being seen inside the staff area raises suspicion at 12.5 per second");
    Check(player.layer==2 && guard.CanSee(actor),"Sight detection includes the player's Ignore Raycast layer");
    guardTick.Invoke(guardHud,null);Check(guardHud.Status.Contains("Harris sees you") && guardHud.Status.Contains("Step outside"),"HUD names the cause and a concrete way to reduce suspicion");
    blocker=GameObject.CreatePrimitive(PrimitiveType.Cube);blocker.name="Temporary sight blocker";blocker.transform.position=new Vector3(6.8f,1.35f,6.04f);blocker.transform.localScale=new Vector3(1,2,.08f);Physics.SyncTransforms();
    Check(!guard.CanSee(actor),"Solid geometry blocks the guard's view even inside the restricted area");suspicion.Step(.25f);Check(suspicion.Level<12.5f && guardHud.Status.Contains("lost sight"),"Breaking sight lowers suspicion and explains why");
    UnityEngine.Object.DestroyImmediate(blocker);blocker=null;Clear();Place(new Vector3(6.8f,.05f,5.7f));guard.transform.rotation=Quaternion.identity;Physics.SyncTransforms();suspicion.Step(2);Check(!suspicion.Seen && suspicion.Level==0,"Guard cannot see a player behind his facing direction");guard.transform.rotation=guardRotation;
    guard.enabled=false;suspicion.Step(2);Check(suspicion.Level==0,"Disabled guard cannot raise suspicion");guard.enabled=true;
    guard.Area.enabled=false;suspicion.Step(2);Check(!suspicion.Inside && suspicion.Level==0,"Disabled restricted area does not produce trespass suspicion");guard.Area.enabled=true;
    Place(new Vector3(6.8f,.05f,-1f));Check(!guard.CanSee(actor),"Player beyond six metres is outside guard sight range");
    foreach(int rate in new[]{30,60,144}){Clear();Place(new Vector3(6.8f,.05f,5.7f));for(int i=0;i<rate*4;i++)suspicion.Step(1f/rate);Check(Mathf.Abs(suspicion.Level-50)<.005f,"Suspicion reaches 50 after four visible seconds at "+rate+" FPS");}
    float before=suspicion.Level;suspicion.Step(-1);suspicion.Step(float.NaN);suspicion.Step(float.PositiveInfinity);Check(suspicion.Level==before,"Invalid elapsed time cannot corrupt suspicion");
    guardTick.Invoke(guardHud,null);string message=(string)actor.GetType().GetField("message",flags).GetValue(actor);Check(message.Contains("Leave before"),"Warning threshold produces a guard warning");
    actor.ShowMessage("sentinel");guardTick.Invoke(guardHud,null);Check((string)actor.GetType().GetField("message",flags).GetValue(actor)=="sentinel","Warning does not repeat every frame");
    clock.SetPaused(true);before=suspicion.Level;suspicion.Step(30);Check(suspicion.Level==before,"Paused prison time freezes suspicion despite elapsed time");clock.SetPaused(false);
    suspicion.Step(100);guardTick.Invoke(guardHud,null);Check(suspicion.Level==100 && suspicion.OrderedOut && guardHud.Heading.Contains("LEAVE NOW"),"Suspicion caps at 100 and produces a persistent order to leave");
    actor.ShowMessage("sentinel");guardTick.Invoke(guardHud,null);Check((string)actor.GetType().GetField("message",flags).GetValue(actor)=="sentinel","An order to leave is not overwritten by a lower-level warning next frame");
    Use(guard,new Vector3(6.8f,.05f,5.7f),guard.transform.position+Vector3.up*1.2f);message=(string)actor.GetType().GetField("message",flags).GetValue(actor);Check(message.StartsWith("Harris:") && message.Contains("marked area"),"Real E targeting reaches the guard and explains how to comply");
    second=new GameObject("Other actor fixture");second.transform.position=new Vector3(50,0,0);var otherCam=new GameObject("Camera").AddComponent<Camera>();otherCam.enabled=false;otherCam.transform.SetParent(second.transform);second.AddComponent<PrisonGame.Prototype.PlayerInteraction>();second.GetComponent<PrisonGame.Prototype.FirstPersonController>().enabled=false;var other=second.AddComponent<PrisonGame.Prototype.GuardSuspicion>();var so=new SerializedObject(other);so.FindProperty("observer").objectReferenceValue=guard;so.FindProperty("clock").objectReferenceValue=clock;so.ApplyModifiedPropertiesWithoutUndo();other.Step(1);Check(other.Level==0 && suspicion.Level==100,"Each actor has separate suspicion with the same guard");
    Place(new Vector3(6.8f,.05f,4.8f));suspicion.Step(1);Check(suspicion.Level==80 && !suspicion.Rising && guardHud.Status.Contains("You left"),"Leaving the area lowers suspicion at 20 per second and changes its explanation");
    guardTick.Invoke(guardHud,null);suspicion.Step(4);guardTick.Invoke(guardHud,null);message=(string)actor.GetType().GetField("message",flags).GetValue(actor);Check(suspicion.Level==0 && message.Contains("cleared"),"Suspicion reaches zero and announces resolution once");
    actor.ShowMessage("sentinel");guardTick.Invoke(guardHud,null);Check((string)actor.GetType().GetField("message",flags).GetValue(actor)=="sentinel","Clear notification does not repeat every frame");
    Place(new Vector3(6.8f,.05f,5.7f));suspicion.Step(1);guardTick.Invoke(guardHud,null);Check(suspicion.Level>0 && ((string)actor.GetType().GetField("message",flags).GetValue(actor)).Contains("rising"),"Re-entering after resolution starts a new observed episode");
    Sell();Supply();Assemble();Sell();Check(request.Delivered==1 && stock.Money==3,"Snack request acceptance, assembly and delivery still work in the guard scene");
    Place(new Vector3(6.8f,.05f,5.7f));suspicion.Step(3);double left=request.MinutesLeft;clock.Advance(10);Check(request.MinutesLeft<left && suspicion.Level>0,"Deadline continues while suspicion is active during gameplay");
    driver.GetType().GetMethod("OnApplicationFocus",flags).Invoke(driver,new object[]{false});before=suspicion.Level;left=request.MinutesLeft;suspicion.Step(10);clock.Advance(10);Check(suspicion.Level==before && request.MinutesLeft==left && Time.timeScale==0,"Focus pause freezes both deadline and suspicion together");
    results.Add("INFO: Real physics sight/capsule movement and synthetic E targeting used. Controlled Step durations test rates and transitions. Temporary second actor checks state separation, not networking. Stop Play resets test state.");
}finally{
    if(blocker!=null)UnityEngine.Object.DestroyImmediate(blocker);if(second!=null)UnityEngine.Object.DestroyImmediate(second);guard.enabled=true;guard.Area.enabled=true;guard.transform.rotation=guardRotation;
    if(keyboard!=null)UnityEngine.InputSystem.InputSystem.RemoveDevice(keyboard);settings.backgroundBehavior=bg;settings.editorInputBehaviorInPlayMode=input;capture.Invoke(movement,new object[]{false});suspicion.enabled=suspicionEnabled;Time.timeScale=1;driver.enabled=driverEnabled;cc.enabled=false;player.transform.SetPositionAndRotation(start,rotation);cc.enabled=true;cam.transform.localRotation=cameraRotation;Physics.SyncTransforms();
}
System.IO.File.WriteAllLines("../docs/images/guard01-suspicion-checks.txt",results);return string.Join("\n",results);
